
# Name of the workflow
name: Deploy Gradio App

# Specifies when the workflow should be triggered
on:
  # Triggers the workflow on every push
  push:
    # Specifies that the workflow should only be triggered on pushes to the 'main' branch
    branches:
      - main

# Defines the jobs for the workflow
jobs:
  # Defines a job named 'build'
  build:
    # Specifies the type of virtual machine to run the job on
    runs-on: ubuntu-latest

    # Defines the steps for the job
    steps:
    # Step 1: Checks out the code from the repository - i.e it gives github access to latest version of my code on the repo
    - name: Checkout code
      uses: actions/checkout@v2

    # Step 2: Builds a Docker image from the Dockerfile in the repository
    - name: Build Docker image
      run: |
        docker build -t my-gradio-app .

    # Step 3: Runs a Docker container from the built Docker image
    - name: Run Docker container
      run: |
        docker run -d -p 5000:7860 my-gradio-app
